version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      prisma:
        applies-to: version-updates
        patterns:
          - "prisma"
          - "@prisma/*"
      react:
        applies-to: version-updates
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"