version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
        prisma:
          applies-to: version-updates
          patterns:
            - "prisma"
            - "@prisma/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"