version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
      typescript-eslint:
        patterns:
          - "typescript"
          - "typescript-eslint"
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"