services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: frontend
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000

  studio:
    build:
      context: .
      dockerfile: Dockerfile
      target: studio
    container_name: studio
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5555:5555

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  default:
    name: racetijden
    driver: bridge
